### ISSUE TITLE
Poboljšati markere na x-osi na Chartu

### ISSUE THREAD

**Issue by xmudrii** [RAF-SI-2021/banka-front#122]
Zbog lakšeg čitanja, poboljšati markere na x-osi na sledeći način:

* 1D: pokazati samo sat (npr. 9:00)
* 5D: pokazati samo mesec i dan (npr. 5. maj)
* 1M: pokazati svakih nekoliko mesec/dan kombinacija (npr. 5 maj, 10. maj, itd.)
* 6M/1Y/YTD/2Y: pokazati samo mesec i godinu (npr. maj 2022)

![image](https://user-images.githubusercontent.com/18719127/167116282-b540b272-fb7a-4e11-a598-3d3554ec2746.png)

**Comment by vmatovic** [comment]
Zar 1D ne prikazuje već sat, ili si mislio da izbacim vremena tipa 10:30?
