### ISSUE TITLE
Radio buttoni ne funkcionišu ispravno ako se više puta promeni izbor

### ISSUE THREAD

**Issue by xmudrii** [RAF-SI-2021/banka-front#124]
Ukoliko, primera radi, odem na stranicu trgovina i par puta promenim između Buy i Sell dogodiće se da se zabode na jednom i da mi ne dozvoli da promenim selekciju. Isto se dešava i kod Chartova.

![image](https://user-images.githubusercontent.com/18719127/167117081-ed18cc4b-8781-4361-bb10-4b7c86e1cdbd.png)

**Comment by snerror** [comment]
Ne mogu vise da repliciram ovaj problem. Ako se opet pojavi neka se otvori ova kartica.
