### ISSUE TITLE
Pregled transakcija

### ISSUE THREAD

**Issue by vmatovic** [RAF-SI-2021/banka-front#158]
Ovo je stranica na koju se ide kad se klikne na tabelu stanja o računu, kako je opisano u tiketu #156 
Pregled transakcija pokazuje sve transakcije (ili samo svoje ako je korisnik agent) i njene elemente za odabranu valutu:

- Račun
- Datum i vreme transakcije
- Order
- User
- Opis transakcije
- Valuta
- Uplata
- Isplata
- Rezervisano
- Rezervisano koristi

Ovo su atributi iz specifikacije, pogledati u Swagger-u šta vraćaju GET metode, tj. šta body ima od atributa. 

Supervizor, za pregled transakcija po valuti se koristi GET http://localhost:8083/api/racun/transakcije/{valuta}, gde je valuta selektovana valuta iz tabele stanja o računu.
Za agenta se koristi GET http://localhost:8083/api/racun/transakcije, koji hvata sve njegove transakcije.

Na kraju tabele, kao poslednji red (na stranici), pokazati sumu kolona Uplata i Isplata.
Treba da se obavi i filtriranje transakcija po datumu, kako je opisano u tiketu #160

**Comment by lmiladinovic99** [comment]
http://localhost:8083/api/racun/transakcije
http://localhost:8083/api/racun/transakcije/{valuta}
Obe rute se koriste i za supervizore i za agente. 
Kod supervizora ce prva ruta vratiti sve transakcije (za sve korisnike) u svim valutama, a druga ruta ce vratiti sve transakcije u prosledjenoj valuti. 
Kod agenta ce prva ruta vratiti sve transakcije (za ulogovanog korisnika) u svim valutama, a druga ce vratiti transakcije ulogovanog korisnika u prosledjenoj valuti. 
Ova dva linka su gotova na backendu.
