### ISSUE TITLE
Stranice za 2FA, zaboravljenu šifru, resetovanje šifre

### ISSUE THREAD

**Issue by vmatovic** [RAF-SI-2021/banka-front#48]
Login i forma za dodavanje novih zaposlenih je završeno.
Prati se dizajn u Figmi: https://www.figma.com/file/TJj2Yde8gcPmanh9zHCEdN/Banka-frontend?node-id=218%3A371
Koristi se **Window** komponenta za renderovanje forme. Pogledati Storybook fajl kako se koristi.

Nakon login-a, koristiti `/api/otp/has/{id}` da se proveri da li je korisnik setupovao 2FA. Ako jeste, redirektuj na 2FA stranicu, a ako nije, redirektuj na Početnu.
Podrazumevano je da je dugme disabled ako forma nije skroz popunjena.

2FA: /2fa
- Pratiti dizajn. Kod se dobija iz aplikacija poput Google Authenticator. Kada se klikne na dugme, koristi `/api/otp/validate` za verifikaciju koda. Ako je true, nastaviti na Početnu stranicu. Ako nije, renderovati **Alert** komponentu na vrhu strane gde je ispisano da validacija nije uspela.

Forget password: /forget-password
- Sadrži textfield za unos mejla. Klikom na dugme treba da se pošalje na mejl link za promenu sifre (link vodi na /change-password).

Resetovanje šifre: /reset-password
- Imamo dva textFielda za novu šifru i ponovljenu šifru. Treba da se validira da li su sifre identicne pre nego sto se posalje poziv. Ukoliko su identicne poslati submit (proveriti sa backom da li je `/user/edit/{id}`). Ako je izmena uspešna, nastaviti na početnu stranicu. Ako nije, renderovati **Alert** komponentu na vrhu strane gde je ispisano da promena šifre nije uspela.

**Comment by psarenac6619rn** [comment]
Cao drugari, ako izuzmemo api pozive stranice za resetovanje sifre i stranica za 2FA je uradnjena
