### ISSUE TITLE
Implementacija Forget Password funkcionalnosti

### ISSUE THREAD

**Issue by xmudrii** [RAF-SI-2021/banka-front#62]
Na Login formi je potrebno dodati link ka Forget Password formi gde korisnik može da zahteva da resetuje svoj password. Nakon toga, korisniku se šalje link ka formi gde može da unese novi password.

U login stranici (fajl je login.jsx) treba dodati link "Zaboravili ste šifru?" između textfielda za šifru i dugmeta za prijavu.

![image](https://user-images.githubusercontent.com/58729033/163669998-e5d52bcf-2eb2-4612-90e3-c9dd781c0196.png)

U folderu pages > dashboard treba da se napravi novi fajl **enter-email.jsx** (možda je najbolje da kopirate login.jsx fajl i da samo preimenujete u enter-email da bi vam služio kao neki template). Forma treba da sadrži textfield email i dugme "Pošaljite mail". Dugme treba da je onemogućeno ako je textfield prazan. Nakon klika na dugme se šalje POST request na link api/user/reset-password (body sadrži samo "email").

![image](https://user-images.githubusercontent.com/58729033/163670148-858ac22d-8946-4c72-81ba-05c91a27105f.png)

**Comment by psarenac6619rn** [comment]
Da li ovo moze da se gasi?
